# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Hacienda < Formula
  desc "🇨🇷 Hacienda es una aplicación que se conecta al API del Ministerio de Hacienda de Costa Rica."
  homepage "https://kevinah95.github.io/hacienda"
  version "0.10.1"
  license "Apache-2.0"

  depends_on "git"
  depends_on "go" => :optional

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/kevinah95/hacienda/releases/download/v0.10.1/hacienda_Darwin_arm64.tar.gz"
      sha256 "439d6e6ca9b2db5cd6522f21c6acc13fb64b955502f2b70ed27404520e827002"

      def install
        bin.install "hacienda"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kevinah95/hacienda/releases/download/v0.10.1/hacienda_Darwin_x86_64.tar.gz"
      sha256 "59ac97c1367b4dba295aa072ab787dd27effabbbe31c231ae06c72994c12fdb2"

      def install
        bin.install "hacienda"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kevinah95/hacienda/releases/download/v0.10.1/hacienda_Linux_arm64.tar.gz"
      sha256 "9a42dc0636bb41c7469f8f802b86a45c90dbeb774cce9269c16f8a5346d560cf"

      def install
        bin.install "hacienda"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/kevinah95/hacienda/releases/download/v0.10.1/hacienda_Linux_x86_64.tar.gz"
      sha256 "0f185b07c95417584d9986f27c07e6cd628f483de3250b4fff3f0fd73c1ed78f"

      def install
        bin.install "hacienda"
      end
    end
  end

  test do
    system "#{bin}/hacienda -v"
  end
end
